server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://192.168.0.130:3306/spring_boot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    initialization-mode: always
logging.level:
  com.zd: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis.mapper/*.xml
---
server:
  port: 9091
spring:
  profiles: dev
---
server:
  port: 9094
spring:
  profiles: prod